### ISSUE TITLE
Package does not interpret dates correctly

### ISSUE THREAD

**Issue by tgb20** [farazkaleemmalik/gocomics-api#4]
When trying to fetch a comic from today's date `2021/12/19` as the format specified `date: [2021,12,19]` the package tries to load the date `2022/0/19`.

This appears to happen for any year. Using the date `2020/12/19` attempts to load `2021/0/19`.

When using the 12th month the year is incremented by 1 and the month is set to 0.

**Comment by numberisnan** [comment]
Merged
